# -*- coding: utf-8 -*-
"""Untitled50.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jQv5ESsFXXTk2u4Tt4d7T-yZkJ09f4dg
"""

from flask import Flask, render_template, request
import os
from topsis_core import run_topsis
import smtplib
from email.message import EmailMessage

app = Flask(__name__)

INPUT_DIR = "input_files"
RESULT_DIR = "results"

os.makedirs(INPUT_DIR, exist_ok=True)
os.makedirs(RESULT_DIR, exist_ok=True)

@app.route("/")
def home():
    return render_template("index.html")

@app.route("/process", methods=["POST"])
def process():
    uploaded_file = request.files["file"]
    weights = request.form["weights"]
    impacts = request.form["impacts"]
    user_email = request.form["email"]

    input_path = os.path.join(INPUT_DIR, uploaded_file.filename)
    output_path = os.path.join(RESULT_DIR, "topsis_output.csv")

    uploaded_file.save(input_path)

    run_topsis(input_path, weights, impacts, output_path)
    mail_result(user_email, output_path)

    return "✅ TOPSIS analysis completed. Result has been emailed."

def mail_result(receiver_email, file_path):
    message = EmailMessage()
    message["Subject"] = "Your TOPSIS Evaluation Result"
    message["From"] = "yourgmail@gmail.com"
    message["To"] = receiver_email
    message.set_content("Attached is the result file generated using TOPSIS method.")

    with open(file_path, "rb") as f:
        message.add_attachment(
            f.read(),
            maintype="application",
            subtype="octet-stream",
            filename="topsis_result.csv"
        )

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login("yourgmail@gmail.com", "APP_PASSWORD")
        server.send_message(message)

if __name__ == "__main__":
    app.run(debug=True)