# -*- coding: utf-8 -*-
"""Untitled50.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jQv5ESsFXXTk2u4Tt4d7T-yZkJ09f4dg
"""

import pandas as pd
import numpy as np

def run_topsis(csv_path, weight_str, impact_str, result_path):
    # Load dataset
    data = pd.read_csv(csv_path)

    # Convert criteria columns to float
    data.iloc[:, 1:] = data.iloc[:, 1:].astype(float)

    weights = np.array([float(w) for w in weight_str.split(",")])
    impacts = impact_str.split(",")

    values = data.iloc[:, 1:].values

    # Step 1: Normalize
    norm_factor = np.sqrt((values ** 2).sum(axis=0))
    normalized_matrix = values / norm_factor

    # Step 2: Apply weights
    weighted_matrix = normalized_matrix * weights

    best = []
    worst = []

    # Step 3: Identify ideal best & worst
    for idx, imp in enumerate(impacts):
        if imp == "+":
            best.append(weighted_matrix[:, idx].max())
            worst.append(weighted_matrix[:, idx].min())
        else:
            best.append(weighted_matrix[:, idx].min())
            worst.append(weighted_matrix[:, idx].max())

    best = np.array(best)
    worst = np.array(worst)

    # Step 4: Distance calculation
    dist_best = np.sqrt(((weighted_matrix - best) ** 2).sum(axis=1))
    dist_worst = np.sqrt(((weighted_matrix - worst) ** 2).sum(axis=1))

    # Step 5: Score & Rank
    performance = dist_worst / (dist_best + dist_worst)

    data["Score"] = performance
    data["Final Rank"] = data["Score"].rank(ascending=False).astype(int)

    data.to_csv(result_path, index=False)